### ISSUE TITLE
[Request] Structure Spawner Items?

### ISSUE THREAD

**Issue by ghost** [yungnickyoung/Ribbits#10]
I absolutely adore this mod and I was wondering if there would be a way to add a way to spawn in the charming little homes they have to integrate them into player made villages easier. Me and my friends have been working to cover an entire island with the village in a sort of animal crossing way and was hoping there would be some form of spawner for the structures (like the Gnumus mod if you've seen that before). Either way whether this can be achieved or not, please keep up the amazing work with this mod.

![2024-07-12_19 00 17](https://github.com/user-attachments/assets/c93d9a39-58c2-4899-b61f-9a12dfca4ffa)

**Comment by yungnickyoung** [comment]
It's an interesting idea, but we don't currently have any plans for such a feature. Seems like that would be a feature better suited for a different mod, e.g. a mod that allows you to create build blueprints and then instantiate them.
