### ISSUE TITLE
Forge's Ribbits requiring Yung's API (Fabric)

### ISSUE THREAD

**Issue by EzequielMTZ-18** [yungnickyoung/Ribbits#12]
tried to use this mod on my forge server but console says  something like "ERROR, THIS MODS REQUIRED Yung's API FABRIC, yungs api is currently not installed"

but why it requires Yungs API if i downloaded the Forge version of ribbits? no sense.
1.20.1

**Comment by TheFairyMan** [comment]
Thank you, this made me find out why the mod was just crashing, and wasn't even displaying what dependency it needed.

I installed the Forge version of Yung's API and it worked both on Client and Server, for 1.20.1.

I have no idea why so many mod creators just don't include the dependencies of their mods on the mod page. 
Thou, it saying that it needs the Fabric version seems like an oversight. Sucks that they left comments disabled on curseForge, so nobody can talk about it there.

**Edit:** The link in case somebody arrives here too looking at why it isn't working: [https://www.curseforge.com/minecraft/mc-mods/yungs-api](url)

**Comment by EzequielMTZ-18** [comment]
oooh thank you, i didnt knew there was a Forge version for Yungs API, anyways the ribbits page doesnt shows that as you said. thanks mate
