### ISSUE TITLE
Lack of propigation mechanic meaning that ribbit villages eventutally die off

### ISSUE THREAD

**Issue by Ceephalon** [yungnickyoung/Ribbits#18]
less a direct error issue but it ties in with some of the other currently open issue reports of spawned ribbits despawning, and random death of ribbits
they definitely need some kind of resistance random game events and ai behavior that will invariably kill said ribbits, say, getting stuck under a lilypad and drowning, wall suffication, and the ilk, 
as such, means to convert or turn nitwit ribbits into the specificly ribbits would be helpful mechanics for ensuring things like the Merchants arent all killed off on a server, meaning all the mod added blocks become inaccessiable to a survival player
as well as some kind of basic propigation mechanic to make sure the village actaully maintains enough of them to not turn into a surprisingly sad ghost town

**Comment by yungnickyoung** [comment]
Ribbits will have passive healing and be unable to drown in the next release (v3.0.1), so that should help their survivability.
