### ISSUE TITLE
[Bug] Wrong Egg Obtain In Creative

### ISSUE THREAD

**Issue by Fyoncle** [yungnickyoung/Ribbits#2]
When middle clicking on a Ribbit to take in creative, EVERY type of Ribbit gives the egg of Sorcerer Ribbit :(

**Comment by yungnickyoung** [comment]
It's a known issue, in the meantime you can get the correct egg via the creative menu tab!

**Comment by Fyoncle** [comment]
Thanks!

**Comment by Fyoncle** [comment]
Fixed with 3.0.1
