### ISSUE TITLE
Any plan backport to 1.19.2 forge?

### ISSUE THREAD

**Issue by QianFuv** [yungnickyoung/Ribbits#7]
Such an excellent mod! If you can backport it, I'm sure players on 1.19.2 will appreciate it!

**Comment by Felsito** [comment]
I have the same opinion, it would be a good mod for my server!

**Comment by TwistedTimes24** [comment]
Would love to see A 1.19.2 forge version of this if possible and add it to A modpack.

**Comment by yungnickyoung** [comment]
Sorry, but we don't have any plans to backport the mod atm
