### ISSUE TITLE
Minecraft (1.20.1) crashes at startup, launching through Modrinth with BetterMC modpack installed

### ISSUE THREAD

**Issue by steviefinn** [yungnickyoung/Ribbits#9]
Hopefully mod compatiblity will be improved. I've been dying to play this mod on my modded world!

Crash log: https://mclo.gs/HxmBYK8

**Comment by yungnickyoung** [comment]
Sorry for the late response, but you're simply missing the [YUNG's API mod](https://legacy.curseforge.com/minecraft/mc-mods/yungs-api/files/5331703) which is a required dependency for Ribbits
